### ISSUE TITLE
Dry::Logger ignores log-payloads passed by block

### ISSUE THREAD

**Issue by wuarmin** [dry-rb/dry-logger#25]
I tried to plugin a `Dry::Logger`-instance at `Faraday's` logging middleware:

```ruby
class MyRepo
  include Deps["logger"]

  def initialize(logger:)
    @logger = logger

    conn = Faraday.new(url: Ots::Slice[:settings].ots_endpoint) do |conn|
      conn.response :logger, logger
    end
  end
end
```

The resulting logs are:
```txt
[services] [INFO] [2023-01-11 09:49:53 +0100] request
[services] [INFO] [2023-01-11 09:49:53 +0100] request
[services] [INFO] [2023-01-11 09:49:53 +0100] response
[services] [INFO] [2023-01-11 09:49:53 +0100] response
```
instead of
```txt
[services] [INFO] [2023-01-11 09:49:53 +0100] request: POST https://www.api.de
[services] [INFO] [2023-01-11 09:49:53 +0100] request: bla bla bla 
[services] [INFO] [2023-01-11 09:49:53 +0100] response: Status 200
[services] [INFO] [2023-01-11 09:49:53 +0100] response: headers etc...
```
`Faraday` passes the log payload by block:

```ruby
logger.info("request") { "hello" }
``` 
Is it expected that `Dry::Logger` differs from Ruby's Default Logger in this area?
https://ruby-doc.org/stdlib-2.4.0/libdoc/logger/rdoc/Logger.html#method-i-info

thanks and best regards

**Comment by solnic** [comment]
This was an oversight. The intention is to have a compatible interface, so we gotta fix it.

**Comment by komidore64** [comment]
I am running into this same situation while using [HTTP.rb](https://github.com/httprb/http).

**Comment by bkuhlmann** [comment]
:bulb: You might want to check out [Cogger](https://alchemists.io/projects/cogger) for this due to having block support built in by default. Cogger is similar in spirit to this gem's Object API but with a lot more features, customization, etc.

**Comment by timriley** [comment]
@komidore64 Thanks for the nudge on this issue, I'll see if I can get a fix for you this week!

**Comment by komidore64** [comment]
@timriley hey that's great news! I was planning to take a crack at it in the next couple days, but I imagine I'll be slower coming to a solution as I'll have to get used to the codebase first.

Thanks for the quick reply <3

**Comment by timriley** [comment]
@komidore64 ohh, in that case, please be my guest! 😍

And instead, I can promise you some very prompt PR reviews. I'm also happy to answer questions. You can jump into our [forum](https://discourse.hanamirb.org) (which now has chat!) to reach me 😄

**Comment by komidore64** [comment]
> ohh, in that case, please be my guest! 😍

Ok! I'll see what I can do.

> And instead, I can promise you some very prompt PR reviews. I'm also
> happy to answer questions. You can jump into our
> [forum](https://discourse.hanamirb.org) (which now has chat!) to reach
> me 😄

Sounds great. Is your preference for me to reach out in the [Hanami
forum](https://discourse.hanamirb.org) as opposed to [dry-rb community
forum](https://discourse.dry-rb.org)? There is a (small, but) [relevant
thread] in the dry-rb community space.

[relevant thread]: https://discourse.dry-rb.org/t/dry-logger-api-compatible-with-ruby-logger/1590

Regardless of communication location, I'm looking forward to working
with you on this. Thanks a bunch!

**Comment by timriley** [comment]
Oh right, I had the wrong forum in mind when I linked that to you! If you have questions, happy for you to do so on the [existing dry-rb forum thread](https://discourse.dry-rb.org/t/dry-logger-api-compatible-with-ruby-logger/1590). :)

**Comment by komidore64** [comment]
@timriley do we need to trigger a job somewhere to get new documentation to appear for `dry-logger` on dry-rb.org?
